### ISSUE TITLE
Sort Text in Paragraphs (Not Columns)

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/SanskritSorting#25]
Extracted from https://github.com/drdhaval2785/SanskritSorting/issues/7

@drdhaval2785 Could we please sort text with `;` delimiters as well?

<a href="https://github.com/gasyoun/gasyoun.github.io/blob/master/reverse20-ouput/upasarga/Whitney-Upasarga.txt">Input</a> / <a href="https://github.com/gasyoun/gasyoun.github.io/blob/master/reverse20-ouput/upasarga/devanagarisorted1.txt
">Output</a>

Because both **as** should go together: **√1 as**; √1 bhuj; √1 ci; √dā; √dhā; √dhāv; √gā; √gṛ; √hā; √hṛ; √kṛ (skṛ); √kṛt; √1 lī; √luṭh; √mā; √1 naś; √nu; √pā; √paś; √pat; √pṛ; √śās; √1 sidh; √śṛ; √1 stu; √1 tan; √1 ukṣ; √vā; √vap; √vid; √1 vṛ; √yu; **√2 as**; √aś;

Now if I have to replace `;` with `\n` I get

```
| ī |
#√1 lī#

| u015b; |
#√aś;#

| ṛ |
#√śṛ#

| u1e5b) |
#√kṛ (skṛ)#
```

The thing is at the end I will have to convert `\n` back to `;` but I will not get where I started, because there are several additional `\n`-s. So no luck. The `√aś;` can be manually cleaned up to `√aś`, but not `√kṛ (skṛ)` - it would have to remain such.

**Comment by gasyoun** [comment]
@drdhaval2785 you do not ignore them in https://github.com/drdhaval2785/SanskritSorting/issues/42 `#arth — 156, 187#` format yet.

**Comment by drdhaval2785** [comment]
@gasyoun use some other delimiter like - to separate the numbers from word.
For single number it would work.
for multiple numbers, separated by a comma, it may not work

**Comment by gasyoun** [comment]
Not to use `—` ok. The commas need replacement with what to work?
