### ISSUE TITLE
conf.php comments

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/SanskritSorting#41]
`Line 5` and `7` should be uncommented by default in conf.php

**Comment by drdhaval2785** [comment]
Not necessary. Right now passing everything from commandline.
Therefore, conf.php is not much relevant for passing input and output destination.

Syntax for Commandline Interface. (This is a CLI tool now) the syntax is
```
php multi13.php outputfolder inputtext morphologicends
php reverse22.php outputfolder inputtext morphologicends
```
Actual examples are
```
php multi13.php d:\sorting d:\sorting\input\input.txt d:\sorting\input\morphologicends.txt
php reverse22.php d:\sorting d:\sorting\input\input.txt d:\sorting\input\morphologicends.txt
```
