### ISSUE TITLE
#asūy sorted above #as

### ISSUE THREAD

**Issue by gasyoun** [drdhaval2785/SanskritSorting#42]
@drdhaval2785 please help. http://gasyoun.github.io/296.txt is the IAST source file, based on that
I wanted to sort http://gasyoun.github.io/296-SLP1.txt

not only is `a` again split of because of some unknown and unseen spaces, but it's `#as` sorted above `#asūy` that is even stranger.

```
| a |
#ac — 137#
#añj — 79#
#aṇ — 118, 144#
#atī — 138, 238#
#apekṣ — 172#

| ﻿ |
#﻿abhī — 230#

| a |
#arc — 42#
#arj — 53, 59, 170#
#arth — 156, 187#
#arṣ — 138#
#arh — 95, 199#
#ar — 42, 53, 59, 95, 122, 138, 156, 170, 187, 199#
#avekṣ — 80, 208, 218#
#aś — 140#
#asūy — 225#
#as — 60, 71, 125, 139, 143, 200, 210, 225#
```

**Comment by gasyoun** [comment]
Same with
```
kam
kar
kart
karś
karṣay
karṣ
kalpay
kalp
kāṅkṣ
kās
kḷp
kram
krīḍ
klid
kliś
kṣi
kṣip
kṣubh
```

**Comment by drdhaval2785** [comment]
This is not an issue. Closing. Noting the 'abhI' issue separately.

**Comment by gasyoun** [comment]
Not as issue why, please explain. Because of https://github.com/drdhaval2785/SanskritSorting/issues/20#issuecomment-59347959 because of `We are not sorting by k, K, g etc. We sort according to ka Ka ga` ?

**Comment by drdhaval2785** [comment]
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=0002
it shows the following ordering.

![capture](https://cloud.githubusercontent.com/assets/5755132/7678313/d32001ca-fd70-11e4-8c61-f619e2707689.PNG)

After every possible vowel after 'ak' is over, they start 'akk'.

This was the original reason why we chose the vowels and consonants separately.


But in the present discussion, there has been an interesting ramification -
In the same dictionary on http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=0001
The ordering of aMS precedes aMSa.
![capture](https://cloud.githubusercontent.com/assets/5755132/7678352/1b76db06-fd71-11e4-83fb-029b26630bcd.PNG)

Hence the need to reopen this issue.

If prima facie looks like 
the words ending with halanta (aMS) precede those ending with halanta+vowel+... (aMSa etc)
But the words having halantas in between follow the words having consonant (akkA follows akOSala)

**Comment by gasyoun** [comment]
`aMS` should come before `aMSa` - have no reason to think otherwise. Neither I have seen it differently in dictionaries.

**Comment by drdhaval2785** [comment]
`$c[$i] = preg_replace('/(\\\u[0-9abcdef]{4})(\\\u094d)$/','!$1$2',$c[$i]);` is the regex added to overcome this hurdle.
Will have to look for potential side-effects

**Comment by gasyoun** [comment]
So it's ready for testing?

**Comment by drdhaval2785** [comment]
Yes

**Comment by gasyoun** [comment]
Some strange side-effects occur.

```
ac
aṇ
an
ar
aś
as
añj
atī
apekṣ
abhī
arc
arj
arth
arṣ
arh
avekṣ
asūy
```

Now `as` is far away from `asūy` - that makes sense even less.

**Comment by drdhaval2785** [comment]
Tried in latest commit.

```
a- (6),
| a |
#aṁś#
#aṁśa#
#aṁśya#
#as#
#asa#
#asūy#
```

This is the output.
This time I leave it for you to check and close the issue
