### ISSUE TITLE
abhI error - conversion to Devanagari / json_encode error

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/SanskritSorting#43]
As an offshoot from #42 there was one issue in which 'abhI' was sorted separately.
I examined it. There seem to be some conversion error while converting it to devanAgarI, because the json_encode gives 'null' in that case.

**Comment by gasyoun** [comment]
Let there be light.

**Comment by drdhaval2785** [comment]
Error was in multi13.php on the following line
`$delimiters = " \-*()@\ ";`
There was a long dash in between which was causing problem in conversion.
Now cleaned up.
